import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { fetchMatches } from '../components/valorantAPI'
import { fetchAccount } from '../components/valorantAPI'
import React, { useEffect, useState } from "react";

const Home: NextPage = () => {
  
  const player = fetchAccount("FrozenSonar", "8838")
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <>
          <p>Nice one dong</p>
          
          <p>{JSON.stringify(player)}</p>
        
          <p> {JSON.stringify(fetchMatches("ap", "FrozenSonar", "8838", "10", null))}</p> 
          
        </>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
