/* eslint-disable react-hooks/exhaustive-deps */
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { fetchMatches } from '../components/valorantAPI'
import { fetchAccount } from '../components/valorantAPI/'
import React, { useEffect, useState } from "react";
import { AccountDetails } from '../components/valorantAPI/fetchAccount/fetchAccount';

const Home: NextPage = () => {
  
  const [playerInfo, setplayerInfo] = useState<AccountDetails>()
  const [matchesInfo, setmatchInfo] = useState<any>()

  useEffect( () => {
    fetchAccount("FrozenSonar", "8838").then((accountDetails: AccountDetails) => {
      setplayerInfo(accountDetails)
    })

   /* fetchMatches("ap", "FrozenSonar", "8838", "10", null).then((matchDetails: any) => {
      setMatchDeets(matchDetails)
    }) */

  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <>
          <p>Nice one dong</p>
          
          <p>{JSON.stringify(playerInfo?.name)}</p>
        
          <p> {}</p> 
          
        </>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
